FinalProjectFirstTest/FinalProjectFirstTest/Controllers/BuyerController.cs
using FinalProjectFirstTest.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Facebook;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FinalProjectFirstTest.Controllers
{
    public class BuyerController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly FinalProjectDbContext _db;
        public BuyerController(IWebHostEnvironment environment, FinalProjectDbContext db)
        {
            _environment = environment;
            _db = db;
        }
        // 買家首頁
        public IActionResult Index()
        {
            return View();
        }
        // 拿首頁資訊
        public List<IndexInfo> getIndexInfo()
        {
            var s = _db.Camping_Areas.Where(x => x.IsAudit == true).Select(x => new IndexInfo
            {
                CampingAreaId = x.Id,
                CampingAreaName = x.Name,
                CampingDes = x.Description,
                PicPath = x.Camping_Area_Pictures.Any() ? x.Camping_Area_Pictures.FirstOrDefault().Path : "", //Reds
                Region = x.Region,
                LowerPrice = Decimal.ToInt32(x.Rooms.Where(y => y.Camping_AreaId == x.Id).OrderBy(z => z.Price_Of_Weekdays).Select(n => n.Price_Of_Weekdays).FirstOrDefault())
            }).ToList();
            return s;
        }
        // 拿 Region
        public object GetDisplayName()
        {
            var a = Region.GetNames<Region>().ToList();
            //a = Enum.GetNames(typeof(Region)).ToList();
            //Console.WriteLine(a);
            //var r = Region.GetValues<Region>();

            return a;
        }
        // 首頁點露營區 ==> 看房型
        [Route("[controller]/[action]/{id}")]
        public IActionResult RoomInfo([FromRoute] int? id)
        {
            if (id != null)
            {
                HttpContext.Session.SetString("caid", id.ToString());
            }
            return View();
        }
        // 拿某露營區的房型資訊
        [HttpGet]
        public RoomInfoViewModel getRoomInfo(RoomInfoViewModel model)
        {
            string caid = HttpContext.Session.GetString("caid");
            int CAid = Convert.ToInt32(caid);

            var hasUserId = User.HasClaim(x => x.Type == "User_Id");

            if (hasUserId)
            {
                int userId = Int32.Parse(User.Claims.FirstOrDefault(x => x.Type == "User_Id").Value);

                var camp = _db.Camping_Areas.Where(x => x.Id == CAid).FirstOrDefault();
                var service = _db.Services.Where(x => x.Camping_AreaId == camp.Id).FirstOrDefault();

                var userFavRoomId = _db.OrderDetails.Where(x => x.UserId == userId && x.Status == Status.Favority).Select(y => y.RoomId).ToList();

                var s = new RoomInfoViewModel
                {
                    UserFavRoomId = userFavRoomId,
                    CAId = camp.Id,
                    CAname = camp.Name,
                    CAaddress = camp.Address,
                    CAphone = camp.Phone,
                    CAdescription = camp.Description,
                    CApicPath = _db.Camping_Area_Pictures.Where(x => x.Camping_AreaId == camp.Id).Select(s => s.Path).ToList(),
                    Wifi = service.Wifi,
                    Breakfast = service.Breakfast,
                    Canopy = service.Canopy,
                    Canteen = service.Canteen,
                    Dinner = service.Dinner,
                    IsCancel = service.IsCancel,
                    Kitchen_Utensils = service.Kitchen_Utensils,
                    Lunch = service.Lunch,
                    Mattress = service.Mattress,
                    Night_Lighting = service.Night_Lighting,
                    No_Equipment = service.No_Equipment,
                    Outdoor_Tables_Chairs = service.Outdoor_Tables_Chairs,
                    Power_Supply = service.Power_Supply,
                    Public_Refrigerator = service.Public_Refrigerator,
                    Tent_Equipment = service.Tent_Equipment,
                    Rooms = _db.Rooms.Where(x => x.Camping_AreaId == camp.Id).Select(z => new Myroom
                    {
                        UserId = userId, // 好像不需要傳userId
                        RoomId = z.Id,
                        RoomName = z.Name,
                        //RoomType = r.RoomType.GetType().GetMember(r.RoomType.ToString()).First().GetCustomAttribute<DisplayAttribute>().GetName(),
                        RoomType = z.RoomType.GetType().GetMember(z.RoomType.ToString()).First().GetCustomAttribute<DisplayAttribute>().GetName(),
                        PriceOfWeekDay = z.Price_Of_Weekdays,
                        Room_Path = _db.Room_Pictures.Where(y => y.RoomId == z.Id).Select(s => s.Path).ToList(),
                        Room_Des = z.Description,
                        RoomStatus = _db.OrderDetails.Where(n => n.UserId == userId && n.RoomId == z.Id && n.Status == Status.Favority).Select(c => c.Status.ToString()).FirstOrDefault()
                    }).ToList()
                };
                return s;
            }
            else
            {
                var camp = _db.Camping_Areas.Where(x => x.Id == CAid).FirstOrDefault();
                var service = _db.Services.Where(x => x.Camping_AreaId == camp.Id).FirstOrDefault();

                //var userFavRoomId = _db.OrderDetails.Where(x => x.UserId == userId && x.Status == Status.Favority).Select(y => y.RoomId).ToList();

                var s = new RoomInfoViewModel
                {
                    //UserFavRoomId = userFavRoomId,
                    CAId = camp.Id,
                    CAname = camp.Name,
                    CAaddress = camp.Address,
                    CAphone = camp.Phone,
                    CAdescription = camp.Description,
                    CApicPath = _db.Camping_Area_Pictures.Where(x => x.Camping_AreaId == camp.Id).Select(s => s.Path).ToList(),
                    Wifi = service.Wifi,
                    Breakfast = service.Breakfast,
                    Canopy = service.Canopy,
                    Canteen = service.Canteen,
                    Dinner = service.Dinner,
                    IsCancel = service.IsCancel,
                    Kitchen_Utensils = service.Kitchen_Utensils,
                    Lunch = service.Lunch,
                    Mattress = service.Mattress,
                    Night_Lighting = service.Night_Lighting,
                    No_Equipment = service.No_Equipment,
                    Outdoor_Tables_Chairs = service.Outdoor_Tables_Chairs,
                    Power_Supply = service.Power_Supply,
                    Public_Refrigerator = service.Public_Refrigerator,
                    Tent_Equipment = service.Tent_Equipment,
                    Rooms = _db.Rooms.Where(x => x.Camping_AreaId == camp.Id).Select(z => new Myroom
                    {
                        //UserId = userId, // 好像不需要傳userId
                        RoomId = z.Id,
                        RoomName = z.Name,
                        //RoomType = r.RoomType.GetType().GetMember(r.RoomType.ToString()).First().GetCustomAttribute<DisplayAttribute>().GetName(),
                        RoomType = z.RoomType.GetType().GetMember(z.RoomType.ToString()).First().GetCustomAttribute<DisplayAttribute>().GetName(),
                        PriceOfWeekDay = z.Price_Of_Weekdays,
                        Room_Path = _db.Room_Pictures.Where(y => y.RoomId == z.Id).Select(s => s.Path).ToList(),
                        Room_Des = z.Description,
                        RoomStatus = "noUserId"
                    }).ToList()
                };
                return s;
            }
        }
        // 收藏
        [HttpPost]
        public bool getFavoriteInfo([FromBody] FavoriteInfoViewModel model)
        {
            int userId = Int32.Parse(User.Claims.FirstOrDefault(x => x.Type == "User_Id").Value);
            var a = _db.OrderDetails.Where(x => x.UserId == userId && x.RoomId == model.favRoomId && x.Status == Status.Favority).FirstOrDefault();

            if (a == null) // 此roomid沒有在此user的收藏裡 ==> 才可收藏
            {
                _db.OrderDetails.Add(new Models.OrderDetail()
                {
                    UserId = userId,
                    RoomId = model.favRoomId,
                    CreateDate = DateTime.Now,
                    StartDate = DateTime.Now,
                    EndDate = DateTime.Now,
                    Status = Status.Favority,
                    Name = "FackName",
                    Phone = "FackPhone"
                });
                _db.SaveChanges();
                return true;
            }
            else
            {
                _db.Remove(a);
                _db.SaveChanges();
                return false;
            }

        }
        public IActionResult MyFav()
        {
            return View();
        }
        public List<Myroom> GetFavorite()
        {
            var userId = Int32.Parse(User.Claims.FirstOrDefault(x => x.Type == "User_Id").Value);


            //var userFavRoomId = _db.OrderDetails.Where(x => x.UserId == userId && x.Status == Status.Favority).Select(y => y.RoomId).ToList();
            var s = from od in _db.OrderDetails.Where(x => x.UserId == userId && x.Status == Status.Favority)
                    join r in _db.Rooms on od.RoomId equals r.Id
                    select new Myroom
                    {
                        RoomId = r.Id,
                        CAId = r.Camping_AreaId,
                        CAName = r.Camping_Area.Name,
                        RoomName = r.Name,
                        Room_Des = r.Description,

FinalProjectFirstTest/FinalProjectFirstTest/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link href="~/test/aaa.ico" rel="shortcut icon" />
	<title>@ViewData["Title"] 來去Camp一晚</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<!--底部原生搬移到此-->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
	<!-- #endregion-->
	@*fullcalendar*@
	@*<link href='fullcalendar/main.css' rel='stylesheet' />*@
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.11.0/main.css">

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.11.0/main.min.js"></script>
	@*vue axios*@
	<script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/axios/0.9.1/axios.js' integrity='sha512-Kg0CewqPNO/ziOJuCq5eyl3P/V6OLz/Lb1I2m+yKS3lHZcGVFN/KOew18rWP+kTsL7haYdaqGjwHQCZrN0heLQ==' crossorigin='anonymous'></script>
	@{ if (!User.IsInRole("Seller")&& !User.IsInRole("Manager"))
		{
			@*vuetify*@
			<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
			<link href="https://cdn.jsdelivr.net/npm/@@mdi/font@6.x/css/materialdesignicons.min.css" rel="stylesheet">
			<link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
			<script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
			<script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>
		}
	}
	@*sweetalert*@
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.9/dist/sweetalert2.all.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.9/dist/sweetalert2.all.min.js"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.9/dist/sweetalert2.css">

	<!-- #endregion -->
	<!-- #region Zhong 0416-->
	<!--cdn jq-->
	@*<link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/sunny/jquery-ui.css">
		<link rel="stylesheet" href="/resources/demos/style.css">
		<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>*@

	<!--icon-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!--icon cdn-->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
	<!--google-icon cdn-->
	<link href="https://fonts.googleapis.com/css?family=Material+Icons" rel="stylesheet">


	<!-- #endregion-->
	<!-- #region layoutRWD-->
	@*<style>



			@@media (max-width: 500px) and (min-width: 200px) {
				header {
					position: fixed;
					width: 100%;
				}

				* {
					font-size: 20px !important;
				}
			}
		</style>*@
	<!-- #endregion -->
</head>
<body>
	<header>
		<!-- #region First navbar -->

		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
			
					
						<a class="navbar-brand" asp-area="" asp-controller="Buyer" asp-action="Index"><img src="~/test/logo.jpeg" style="width:150px; height:70px ;padding:-3px"></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
								aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
					
				

			<!-- 這一行是靠右邊的-->
			<div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
				<ul class="navbar-nav ml-auto">
					<!-- #region 登入登出 註冊 NavBar this is right-->
					@{
						if (User.Identity.IsAuthenticated)
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Login_Register" asp-action="Logout">登出</a>
							</li>
						}
						else
						{

							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
									註冊/登入
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
									<a class="dropdown-item" asp-area="" asp-controller="Buyer" asp-action="register">買家</a>
									<a class="dropdown-item" asp-area="" asp-controller="Login_Register" asp-action="LoginRegister">賣家</a>
								</div>
							</li>

						}
					}
					<!-- #endregion-->
				</ul>
			</div>
		</nav>
		@{ if (User.Identity.IsAuthenticated)
			{

				<!-- 第二導航  頁面  使用VS預設 -->
				<nav class="navbar navbar-expand-md navbar-dark bg-dark">
					<div class="mx-auto order-0">
						<ul class="navbar-nav ml-auto">
							<!-- #region Buyer Nav-->
							@{if (User.IsInRole("User"))
								{
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Buyer" asp-action="Index">首頁</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Buyer" asp-action="BOrderDetail">訂單</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Buyer" asp-action="myFav">收藏</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Buyer" asp-action="userInfo">基本資料</a>
									</li>
								}
								<!-- #endregion -->
								<!-- #region Admin Nav -->
								if (User.IsInRole("Manager"))
								{
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Manager" asp-action="ManagerOrderDetails">訂單管理</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Manager" asp-action="Get_Unaudited_Campingarea">審核露營區</a>
									</li>
								}
								<!-- #endregion-->
								<!-- #region Seller nav-->
								if (User.IsInRole("Seller"))
								{
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Order_Detail" asp-action="Seller_OrderDetail">訂單管理</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Create_Camping_Area" asp-action="CampingArea">建露營區</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Camping_Information" asp-action="CampingInformation">露營區/房型</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Room_Condition" asp-action="RoomCondition">房況</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Seller_Info" asp-action="SellerInfo">基本資料</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-white" asp-area="" asp-controller="Chart" asp-action="Chart">金額報表</a>
									</li>
								}
								<!-- #endregion-->
							}
						</ul>

					</div>

				</nav>
			} }
		<!--  #endregion -->
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	@*<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - 來去Camp一晚 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>*@
</body>
</html>